FROM ubuntu:20.04

# Ubuntuのパッケージ処理
RUN apt-get update \
&&  apt-get install -y\
    git

#Ubuntu環境を日本語化
RUN apt install -y language-pack-ja\
&&  apt-get install -y locales\
&&  locale-gen ja_JP.UTF-8\
&& echo "export LANG=ja._JP.UTF-8" >> ~/.bashrc

# localeの設定
ENV LANG ja_JP.UTF-8
ENV LANGUAGE ja_JP:ja
ENV LC_ALL=ja_JP.UTF-8

CMD bash