FROM postgres:15rc1-alpine

# localeの設定
  ARG DB_LANG=en_US
  RUN localedef -i $DB_LANG -c -f UTF-8 -A /usr/share/locale/locale.alias $DB_LANG.UTF-8
  ENV LANG &DB_LANG.utf8
  ENV LANG=en_US.UTF-8
  
# ENV POSTGRES_USER postgres
# ENV POSTGRES_DB postgres
# ENV PGDATA /var/lib/postgresql/data/pgdata
# ENV POSTGRES_INITDB_ARGS --data-checksums --encoding=UTF-8
